package com.bussanq.kubewolf.api.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseModelTpl<M extends BaseModelTpl<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setImage(java.lang.String image) {
		set("image", image);
		return (M)this;
	}
	
	public java.lang.String getImage() {
		return getStr("image");
	}
	
	public M setPort(java.lang.String port) {
		set("port", port);
		return (M)this;
	}
	
	public java.lang.String getPort() {
		return getStr("port");
	}
	
	public M setReplicas(java.lang.Integer replicas) {
		set("replicas", replicas);
		return (M)this;
	}
	
	public java.lang.Integer getReplicas() {
		return getInt("replicas");
	}
	
	public M setCmd(java.lang.String cmd) {
		set("cmd", cmd);
		return (M)this;
	}
	
	public java.lang.String getCmd() {
		return getStr("cmd");
	}
	
	public M setEnv(java.lang.String env) {
		set("env", env);
		return (M)this;
	}
	
	public java.lang.String getEnv() {
		return getStr("env");
	}
	
	public M setModelPath(java.lang.String modelPath) {
		set("model_path", modelPath);
		return (M)this;
	}
	
	public java.lang.String getModelPath() {
		return getStr("model_path");
	}
	
	public M setCpu(java.lang.Integer cpu) {
		set("cpu", cpu);
		return (M)this;
	}
	
	public java.lang.Integer getCpu() {
		return getInt("cpu");
	}
	
	public M setMem(java.lang.Integer mem) {
		set("mem", mem);
		return (M)this;
	}
	
	public java.lang.Integer getMem() {
		return getInt("mem");
	}
	
	public M setGpu(java.lang.Integer gpu) {
		set("gpu", gpu);
		return (M)this;
	}
	
	public java.lang.Integer getGpu() {
		return getInt("gpu");
	}
	
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public M setOutUrl(java.lang.String outUrl) {
		set("out_url", outUrl);
		return (M)this;
	}
	
	public java.lang.String getOutUrl() {
		return getStr("out_url");
	}
	
	public M setInUrl(java.lang.String inUrl) {
		set("in_url", inUrl);
		return (M)this;
	}
	
	public java.lang.String getInUrl() {
		return getStr("in_url");
	}
	
	public M setCustom(java.lang.String custom) {
		set("custom", custom);
		return (M)this;
	}
	
	public java.lang.String getCustom() {
		return getStr("custom");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
}

