apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcu-device-plugin-daemonset
spec:
  selector:
    matchLabels:
      name: dcu-hami-ds
  template:
    metadata:
      labels:
        name: dcu-hami-ds
    spec:
      serviceAccountName: dcu-device-plugin
      hostPID: true
      imagePullSecrets:
        - name: bqai
      hostNetwork: true
      nodeSelector:
        gpu_dcu: "on"
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.bq.com/ai
        operator: Exists
      containers:
      - image: {{ .Values.imagePrefix }}/dcu-vgpu-device-plugin:v1.0.6
        #command: ["/bin/bash","-c","source /opt/hygondriver/env.sh && sleep infinity"]
        command: ["/root/k8s-device-plugin"]
        name: dcu-hami-cntr
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: HYGONPATH
            value: /opt/dtk
          - name: BASH_ENV
            value: ~/.bashrc
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            drop: ["ALL"]
            add: ["SYS_ADMIN"]
        volumeMounts:
          - name: dp
            mountPath: /var/lib/kubelet/device-plugins
          - name: sys
            mountPath: /sys
          - name: hwpath
            mountPath: /usr/share/hwdata
          - name: hygonloc
            mountPath: /opt/hygondriver/
          - name: lib
            mountPath: /usr/local/vgpu
          - name: hyhal
            mountPath: /opt/hyhal
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys
          hostPath:
            path: /sys
        - name: hwpath
          hostPath:
            path: /usr/share/hwdata
        - name: hygonloc
          hostPath:
            path: /opt/dtk
        - name: lib
          hostPath:
            path: /usr/local/vgpu
        - name: hyhal
          hostPath:
            path: /opt/hyhal

